security:
    role_hierarchy:
        ROLE_MEMBER: ROLE_USER
        ROLE_BUREAU: ROLE_MEMBER
        ROLE_SECRETAIRE: ROLE_BUREAU
        ROLE_TRESORIER: ROLE_BUREAU
        ROLE_PRESIDENT: ROLE_BUREAU
        ROLE_ADMIN: [ROLE_SECRETAIRE, ROLE_TRESORIER, ROLE_PRESIDENT]
    providers:
        lapinou:
            entity:
                class: StrolladPrestagesBundle:Utilisateur
                property: username

    encoders:
        Strollad\PrestagesBundle\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:     true

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_BUREAU }
